/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TailorJobIdRouteImport } from './routes/tailor/$jobId'
import { Route as JobsNewRouteImport } from './routes/jobs/new'
import { Route as ExportTailoredCvIdRouteImport } from './routes/export/$tailoredCvId'
import { Route as EditorTailoredCvIdRouteImport } from './routes/editor/$tailoredCvId'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TailorJobIdRoute = TailorJobIdRouteImport.update({
  id: '/tailor/$jobId',
  path: '/tailor/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsNewRoute = JobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExportTailoredCvIdRoute = ExportTailoredCvIdRouteImport.update({
  id: '/export/$tailoredCvId',
  path: '/export/$tailoredCvId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorTailoredCvIdRoute = EditorTailoredCvIdRouteImport.update({
  id: '/editor/$tailoredCvId',
  path: '/editor/$tailoredCvId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/upload': typeof UploadRoute
  '/editor/$tailoredCvId': typeof EditorTailoredCvIdRoute
  '/export/$tailoredCvId': typeof ExportTailoredCvIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/tailor/$jobId': typeof TailorJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/upload': typeof UploadRoute
  '/editor/$tailoredCvId': typeof EditorTailoredCvIdRoute
  '/export/$tailoredCvId': typeof ExportTailoredCvIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/tailor/$jobId': typeof TailorJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/upload': typeof UploadRoute
  '/editor/$tailoredCvId': typeof EditorTailoredCvIdRoute
  '/export/$tailoredCvId': typeof ExportTailoredCvIdRoute
  '/jobs/new': typeof JobsNewRoute
  '/tailor/$jobId': typeof TailorJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/upload'
    | '/editor/$tailoredCvId'
    | '/export/$tailoredCvId'
    | '/jobs/new'
    | '/tailor/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/upload'
    | '/editor/$tailoredCvId'
    | '/export/$tailoredCvId'
    | '/jobs/new'
    | '/tailor/$jobId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/upload'
    | '/editor/$tailoredCvId'
    | '/export/$tailoredCvId'
    | '/jobs/new'
    | '/tailor/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  UploadRoute: typeof UploadRoute
  EditorTailoredCvIdRoute: typeof EditorTailoredCvIdRoute
  ExportTailoredCvIdRoute: typeof ExportTailoredCvIdRoute
  JobsNewRoute: typeof JobsNewRoute
  TailorJobIdRoute: typeof TailorJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tailor/$jobId': {
      id: '/tailor/$jobId'
      path: '/tailor/$jobId'
      fullPath: '/tailor/$jobId'
      preLoaderRoute: typeof TailorJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/new': {
      id: '/jobs/new'
      path: '/jobs/new'
      fullPath: '/jobs/new'
      preLoaderRoute: typeof JobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/export/$tailoredCvId': {
      id: '/export/$tailoredCvId'
      path: '/export/$tailoredCvId'
      fullPath: '/export/$tailoredCvId'
      preLoaderRoute: typeof ExportTailoredCvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$tailoredCvId': {
      id: '/editor/$tailoredCvId'
      path: '/editor/$tailoredCvId'
      fullPath: '/editor/$tailoredCvId'
      preLoaderRoute: typeof EditorTailoredCvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  UploadRoute: UploadRoute,
  EditorTailoredCvIdRoute: EditorTailoredCvIdRoute,
  ExportTailoredCvIdRoute: ExportTailoredCvIdRoute,
  JobsNewRoute: JobsNewRoute,
  TailorJobIdRoute: TailorJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
